### ISSUE TITLE
Bonjour!

### ISSUE THREAD

**Issue by pc1984** [anisite/plugin.infologique.TVAgo#1]
Bonjour,

Je voulais savoir comment installer votre addiciel sans fichier .zip?

Merci!

**Comment by pc1984** [comment]
ok j'ai finalement compris comment faire! 

Toutefois les liens ne semblent pas fonctionner... :(

**Comment by anisite** [comment]
Non, effectivement, le plugin n'est pas fonctionnel, c'est pour ça qu'il n'est pas dans le Dépot Québec. Il n'y a pas de date prévue de disponibilité et ce n'est même pas certain à l'heure actuelle qu'il soit complété.

**Comment by pc1984** [comment]
Merci de la réponse rapide! 
Si je connais quelqu'un qui pourrait se pencher sur ce plugin, est-ce que vous me donnez la permission?

**Comment by anisite** [comment]
Je n'ai pas de permission à donner, c'est du code ouvert... TVA ne m'appartient pas!

**Comment by MaximeLussier** [comment]
v1.0.3 ou v1.0.4 fonctionnel
