### ISSUE TITLE
aide pour faire la meme chose avec radio canada

### ISSUE THREAD

**Issue by mgendron23** [anisite/plugin.infologique.TVAgo#11]
Salut, 

j'aimerais ultimement creer un addon pour kodi qui serait en mesure de extraire les lien de difusion live, de tva, radio canada, v et telequebec. 

Mon gros probleme, trouver le URL du video
As tu envi d'aider un newbie ?
Merci

**Comment by MaximeLussier** [comment]
Bonne chance! Tu peux utiliser le code python de l'addon comme base. La version 1.0.4 supporte les DRM et le inputstream adaptatif
