### ISSUE TITLE
TVA Montréal

### ISSUE THREAD

**Issue by Daragott** [anisite/plugin.infologique.TVAgo#12]
Bonjour, TVA Montréal installé sur Kodi dernière version, mais ne fonctionne plus depuis 2 jours.  Je ne sait pas si ça peut vous servir comme information supp;émentaire, mais avec IPTV, TVA Montréal n'a jamais fonctionné depuis que je l'ai installé cette semaine. Merci

Daragott.
nobel230qc@gmail.com

**Comment by MaximeLussier** [comment]
J'ai une nouvelle version en développement, Une fois relâchée faudrait voir si ça corrige le problème

**Comment by Daragott** [comment]
Merci,, je suis nouveau dans l utilisation d'une boite androïde, j'ai installé quelques bonnes applications, si jamais TVA peut fonctionné, alors, fini la câble pour moi, je vais tout avoir avec ma box. Bonne journée

**Comment by JustBeta** [comment]
Bonjour, je n'ai pas le direct de TVA, le reste semble fonctionné.
L'addons, est-il encore suivi ?

Merci.

**Comment by MaximeLussier** [comment]
Bonjour, 
Dépend de la version de Kodi et du Addon mais je viens de tester et mon collègue aussi et le Direct fonctionne présentement. TVA sont très mauvais à garder le direct fonctionnel... habituellement, après 24h c'est revenu.

**Comment by MaximeLussier** [comment]
Vous pouvez aussi essayer la version 1.0.4 qui supporte les DRM et le inputstream adaptatif.

**Comment by JustBeta** [comment]
Merci pour ton retour, j'ai mis a jour mes addons. Pour l'instant le direct n'a pas l'air fonctionnel, mais je vais refaire un test d'ici 24 h (ou plus)
mais, déjà cela me semble plus positif, j'avais des dysfonctionnements sur les replay qui on disparu.
J'avais la 1.03 et inputstream (non adaptive)

**Comment by MaximeLussier** [comment]
Ici ça fonctionne encore... Si tu as encore des problèmes, faudrait activer le débogage et fournir le log. Il est possible qu'il y ait des particularités par région... 
Je test juste de Sherbrooke.

**Comment by JustBeta** [comment]
Moi je suis dans le sud de la France, j'utilise un VPN pour y avoir accès. Je viens de refait un test, et je me suis aperçu que le direct été dans un état "unwached". Je l'ai sélectionné et maintenant cela fonctionne correctement. (je ne connaissais pas cette fonction dans kodi)
Merci pour le temps que vous m'avez accordé.
