### ISSUE TITLE
Nouveau site tva plus...

### ISSUE THREAD

**Issue by kebekois** [anisite/plugin.infologique.TVAgo#13]
Bonjours, vous avez une solution pour https://www.qub.ca/tvaplus, car quand on va sur http://video.tva.ca 
ça nou envoie automatiquement sur https://www.qub.ca/tvaplus donc l'application de plugin.infologique.TVAgo ne fonctionne plus...

**Comment by MaximeLussier** [comment]
@kebekois Semble possible de faire quelque chose... Va falloir que j'y mettes du temps... Reste à en trouver.

**Comment by MaximeLussier** [comment]
Mais l'addon TVA semble encore fonctionner pour l'instant...

**Comment by MaximeLussier** [comment]
@kebekois, peux tu valider que l'addon fonctionne encore pour toi?

**Comment by kebekois** [comment]
j'ai juste une vingtaine d'émission du tricheur seulement et rien d'autres dans attrapage !

**Comment by kebekois** [comment]
et les autres répertoires j'ai rien dedans

**Comment by MaximeLussier** [comment]
Ok donc, il semble que tout ce qui est "vieux" + le live fonctionne encore mais le nouveau contenu n'est plus ajouté...
Je vais devoir regarder Qub alors...

**Comment by JustBeta** [comment]
Juste pour info, je subi le meme problème, mais cependant j'avais fait un favori sur le rattrapage les episode "les feux de l'amour".
Dans ce favori, je retrouve les nouveaux episode fonctionnel que je n'ai pas en passant directement par l'addon.

**Comment by anisite** [comment]
@kebekois l'application a été mise à jour ce soir, est-ce possible de nous tenir informé de vos essais? Merci
