### ISSUE TITLE
Support Kodi 19 - Python 3

### ISSUE THREAD

**Issue by Kameleau** [anisite/plugin.infologique.TVAgo#14]
Bonjour, Kodi 19 est maintenant rendu en RC1, pensez-vous rendre le plug-in TVA compatible avec Kodi 19 qui exige que les addons soit en Python 3?

Merci!

**Comment by anisite** [comment]
@Kameleau c'est corrigé depuis ce soir, est-ce possible de me tenir au courant si vous le testez ? merci

**Comment by orzix25** [comment]
Bonjour tva en direct ne fonctionne plus depuis vendredi soir ou nuit 5 mars. Merci

**Comment by Kameleau** [comment]
Pour moi le plugin TVA fonctionne bien incluant le direct que je viens juste d'essayer.

Merci!
