### ISSUE TITLE
Tva+ ne fonctionne plus

### ISSUE THREAD

**Issue by erikatremblay** [anisite/plugin.infologique.TVAgo#23]
J’ai du aller remettre la version 2.0.4 pour qu’il fonctionne car la version 2.0.5 ne fonctionne plus. 

Merci

**Comment by anisite** [comment]
Avec quelle version de Kodi?

Normalement ça fonctionne sur 19 et 20.

**Comment by erikatremblay** [comment]
Kodi 18.9.

je n’ai pas encore fait de switch a kodi 19 trop d’applications que j’utilise n’ont pas migrer encore 🤦‍♀️ pourtant la version 2.0.4 de tva+ fonctionne

**Comment by erikatremblay** [comment]
De plus,  il me semble que Tele-Quebec ne fonctionne pas sur kodi 19. 🤔

**Comment by anisite** [comment]
Libre à vous de rester sur la 2.0.4, sur la page https://github.com/anisite/DepotQuebec il y a bien une note à ce sujet:
⚠️ Note importante: La fin support de Kodi 18.x est prévue pour la fin de l'année 2021, aucune mise à jour spécifique à la version 18.9 ne sera faite en 2022. Kodi 19 ayant à ce moment 1 an. Notez aussi que tout add-on peut être abandonné à tout moment si l'effort de maintient est trop grand.

**Comment by erikatremblay** [comment]
D’accord. Je vais migrer à kodi 19.

**Comment by anisite** [comment]
je viens de pousser un fix dans le code, mais il ne sera pas intégré ce matin, je vais essayer de livrer ça sous peu

**Comment by erikatremblay** [comment]
Ok merci

**Comment by anisite** [comment]
c'est corrigé version 2.0.6

**Comment by erikatremblay** [comment]
Merci
