### ISSUE TITLE
App non fonctionnel

### ISSUE THREAD

**Issue by boiss** [anisite/plugin.infologique.TVAgo#26]
Le contenu dans le menu TVA n’est plus disponible, je vais vérifier le code pour voir si je peux fixer avec une petite pull request

**Comment by erikatremblay** [comment]
Effectivement plus aucune émissions apparaît pourtant les autres catégories tel addik, casa, tva sport, evasion, etc.. les emissions s’affichent mais pas TVA

**Comment by KodiTopQuebec** [comment]
même chose ici , par contre j'avais mis des favoris dans kodi et ils sont fonctionnelles

**Comment by boiss** [comment]
À première vue, changer le slug /tva pour /accueil/qubtv-emissions dans l'API retournerait pas mal la même chose.. je ne suis pas développeur Kodi, mais je peux essayer de faire une PR avec ceci.

TVA semble avoir changé son slug par défaut, et celui-ci retoune aucune entrées dans le JSON, alors que l'autre "semble" retourner pas mal tout.

@anisite @MaximeLussier 

Je viens de faire une PR, ca fonctionne de mon coté avec la modif. 

Il ne resterait qu'à merger le tout, la modif ne fait que 2 lignes, et je ne suis pas programmeur python, donc svp vérifiez ce que j'ai fait, j'ai tout de même quelques connaissances en prog...

**Comment by anisite** [comment]
merci @boiss c'est mergé et en PROD

**Comment by boiss** [comment]
Fait plaisir! Quand je peux aider je vais vous donner un coup de main!
