### ISSUE TITLE
Plugin pour videos.tva.ca

### ISSUE THREAD

**Issue by service-paradis** [anisite/plugin.infologique.TVAgo#3]
Salut,

J'ai vu que tu avais commencé un plugin pour videos.tva.ca. J'en ai également un fonctionnel. Je viens de l'ajouter à Github, tu peux le voir à l'adresse https://github.com/service-paradis/plugin.tva.videos

Il me reste beaucoup d'améliorations à y apporter (cache, descriptions, etc). Je l'avais fait pour mon usage personnel. J'aimerais beaucoup avoir ton avis! 

Crois-tu que je devrais le publier sur DépotQuébec?

Au plaisir,

**Comment by mathieugouin** [comment]
Est-ce possible de l'essayer?  Je peux aider un peu aussi si besoin, je connais python, mais je n'ai jamais développé de addon Kodi.

Merci d'avance!

**Comment by service-paradis** [comment]
@mathieugouin Oui, tu peux te rendre à l'adresse https://github.com/service-paradis/plugin.tva.videos et cliquer sur le bouton vert « Clone or download ». Tu peux ensuite faire « Download as zip ».

Une fois téléchargé, tu pourras installer l'addon à partir de ce fichier zip. Il apparaîtra donc dans ta liste d'addons. Il reste encore plusieurs choses à améliorer, alors n'hésite pas à faire des « pull requests »!

**Comment by mathieugouin** [comment]
@service-paradis Super, merci.  Je regarde ça et je te tiens au courant!
