### ISSUE TITLE
Tva et VPN

### ISSUE THREAD

**Issue by JimboMTL** [anisite/plugin.infologique.TVAgo#9]
Salut, j'ai une question. J'ai ajouté un vpn (ip vanish) a ma box et si il est actif tva en direct ne fonctionne pas malgré que je garde un ip de Montréal. As-tu une idée?

**Comment by dave-dube** [comment]
Je vis exactement le même problème.  Mais pas seulement avec TVA. Je le vis également avec TOUT.TV entre autre.. Et si je déconnecte mon VPN tout se met à bien fonctionner..  Moi j'utilise SurfShark comme VPN.   J'ai l'impression que ca un lien avec les settings du VPN .. mais je ne trouve pas.

**Comment by anisite** [comment]
Salut, difficile de savoir, ce ne sont pas mes serveurs, ils ont p-e des blacklist de plage d'ip de vpn...
